# Generated by Django 4.0.4 on 2022-10-01 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Username', models.CharField(max_length=50)),
                ('Query', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('Items', models.TextField(max_length=1400)),
                ('Email', models.EmailField(default='', max_length=254)),
                ('First_name', models.CharField(max_length=33)),
                ('Last_name', models.CharField(max_length=33)),
                ('Username', models.CharField(max_length=33)),
                ('Address_1', models.TextField(max_length=1000)),
                ('Address_2', models.TextField(max_length=1000)),
                ('State', models.CharField(max_length=24)),
                ('City', models.CharField(max_length=24)),
                ('Zip_Code', models.CharField(max_length=6)),
                ('Phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('Amount', models.CharField(default=0, max_length=14)),
                ('Json', models.CharField(default='', max_length=1400)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Update',
            fields=[
                ('Update_Id', models.AutoField(primary_key=True, serialize=False)),
                ('Order_Id', models.IntegerField(default='')),
                ('Update', models.TextField(max_length=6000)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_Name', models.CharField(max_length=50)),
                ('Category', models.CharField(max_length=14)),
                ('Price', models.IntegerField()),
                ('Description', models.TextField(max_length=300)),
                ('Publish_Date', models.DateField()),
                ('Image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Review', models.TextField(max_length=250)),
                ('Rating', models.CharField(default=0, max_length=12)),
                ('Date', models.DateField(auto_now_add=True)),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
