# Generated by Django 4.0.4 on 2022-10-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_message_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock_Details',
            field=models.CharField(choices=[('Available', 'Available'), ('Out Of Stock', 'Out Of Stock')], default='Available', max_length=12),
        ),
    ]
